.PHONY: clean All

All:
	@echo "----------Building project:[ lab02 - Debug ]----------"
	@cd "lab02" && "$(MAKE)" -f  "lab02.mk"
clean:
	@echo "----------Cleaning project:[ lab02 - Debug ]----------"
	@cd "lab02" && "$(MAKE)" -f  "lab02.mk" clean
